# Generated by Django 2.2.4 on 2019-11-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ifmodify',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
